export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const GET_LANGS_SUCCESS = 'GET_LANGS_SUCCESS';
export const GET_SELECTED_LANGS_DONE = 'GET_SELECTED_LANGS_DONE';
export const SAVE_SELECTED_LANGS_DONE = 'SAVE_SELECTED_LANGS_DONE';

export const GET_AUTHOR_SUCCESS = 'GET_AUTHOR_SUCCESS';
export const SEARCH_AUTHORS_SUCCESS = 'SEARCH_AUTHORS_SUCCESS';
export const GET_AUTHOR_BOOKS_SUCCESS = 'GET_AUTHOR_BOOKS_SUCCESS';
export const SEARCH_BOOKS_SUCCESS = 'SEARCH_BOOKS_SUCCESS';

