export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const GET_AUTHOR_SUCCESS = 'GET_AUTHOR_SUCCESS';
export const SEARCH_AUTHORS_SUCCESS = 'SEARCH_AUTHORS_SUCCESS';
export const GET_AUTHOR_BOOKS_SUCCESS = 'GET_AUTHOR_BOOKS_SUCCESS';

